modLoader="javafml"
loaderVersion="${forge_loader_version_range}"
license="All rights reserved"
issueTrackerURL="https://github.com/TwelveIterationMods/TrashSlot/issues"

[[mods]]
modId="trashslot"
version="${mod_version}"
displayName="TrashSlot"
displayURL="https://mods.twelveiterations.com/mc/trashslot"
logoFile="trashslot-icon.png"
credits="BlayTheNinth"
authors="BlayTheNinth"
description='''
Adds a trash slot to the inventory screen that allows deletion of unwanted items.
'''

[[dependencies.trashslot]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.trashslot]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.trashslot]]
    modId="balm"
    mandatory=true
    versionRange="${balm_version_range}"
    ordering="NONE"
    side="BOTH"
